CREATE TABLE KH_STUDENT(
	STD_NO NUMBER PRIMARY KEY,
    STD_NAME NVARCHAR2(5) NOT NULL,
    STD_AGE NUMBER NOT NULL,
    MAJOR NVARCHAR2(10) NOT NULL,
    ENT_DATE DATE DEFAULT SYSDATE
);

SELECT * FROM KH_STUDENT;

 
CREATE SEQUENCE SEQ_STUDENT
START WITH 1
INCREMENT BY 1
MAXVALUE 150  
NOMINVALUE     
NOCYCLE        
NOCACHE;       

